from sqlalchemy import Column, Text
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class DBLogs(Base):
    """
    Defines the table schema for storing the logs generated by OAtlas.

    Columns:
            1. `session_id`: A unique identifier for the current session
            2. `function_called`: The name of the function called
            3. `function_output`: The output of the function called

    The `function_called` and the `function_output` are maintained as a stack for a single session ID. This means, we keep stacking the
    function call and along with that its output at the end of each run and finally return it when the user asks for it.

    Why are we logging?:
            1. Its useful in making reports (which is coming up soon)
            2. The logs will help in analysis.

    The idea is to create an analysis module as well which will make oatlas a full `aggregator-analysis` tool.

    """

    __tablename__ = "DBLogs"

    session_id = Column(Text, primary_key=True)
    function_called = Column(Text, nullable=False)
    function_output = Column(Text, nullable=False)

    def __repr__(self):
        return f"DBLogs<session_id: {self.session_id}, function_called: {self.function_called}, function_output: {self.function_output}>"
